# Generated by cpp11: do not edit by hand

cpp_burn_sparse <- function(wkb_list, xmin, ymin, xmax, ymax, ncol, nrow) {
  .Call(`_controlledburn_cpp_burn_sparse`, wkb_list, xmin, ymin, xmax, ymax, ncol, nrow)
}

cpp_controlledburn_init <- function() {
  invisible(.Call(`_controlledburn_cpp_controlledburn_init`))
}

cpp_scanline_burn <- function(wkb_list, xmin, ymin, xmax, ymax, ncol, nrow) {
  .Call(`_controlledburn_cpp_scanline_burn`, wkb_list, xmin, ymin, xmax, ymax, ncol, nrow)
}
