# Generated by cpp11: do not edit by hand

cpp_scanline_burn <- function(wkb_list, xmin, ymin, xmax, ymax, ncol, nrow, mode) {
  .Call(`_controlledburn_cpp_scanline_burn`, wkb_list, xmin, ymin, xmax, ymax, ncol, nrow, mode)
}
