on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check-container

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container: ghcr.io/hypertidy/gdal-r-full:latest
    name: gdal-r-full

    permissions:
      contents: read
      packages: read

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
